server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_NOTIFICATION:localhost}:${DB_PORT_NOTIFICATION:5466}/notification_db
    username: notification_user
    password: notification_pass
